---
- hosts: all
  user: adritake
  become: yes
  become_user: root

  vars:
    - packages: ["nodejs","git","npm"]
    - project_location: /home/adritake/projects

  tasks:
    - name: Install {{ packages }}
      become: yes
      become_user: root
      apt:
        name: "{{ packages }}"
        state: present

    - name: Create project location
      become: yes
      become_user: root
      file:
        path: "{{ project_location }}"
        state: directory

    - name: Download repository
      git:
        repo: https://github.com/adritake/CC_UGR_Personal.git
        dest: "{{ project_location}}"

    - name: Install dependencies
      npm:
        path: "{{ project_location }}"

    - name: Install pm2
      become: yes
      become_user: root
      command: npm install pm2 -g

    - name: Start service
      become: yes
      become_user: root
      command: pm2 start {{ project_location }}/IssueService.js -- production
